#!/bin/bash
command=""
for arg in "$@"
do 
    if [ "${arg/ /}" = "$arg" ] # 如果参数包含空格
    then
        command="$command""$arg"
    else
        command="$command \"$arg\""
    fi
done
command="$command 1>~/.myapp.log 2>&1 &"
# echo $command
eval $command
#$* 1>~/.myapp.log 2>&1 &
# eval $* 1>~/.myapp.log 2>&1 &
